spring.application.name=@project.name@
spring.data.mongodb.uri=${MONGODB_ATLAS_CONNECTION_STRING:mongodb://mongo-portal-gni:27017/db-cad-users}
spring.data.mongodb.database=${DB_USER_NAME:db-cad-users}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER_URL:http://localhost:8080/auth-server}
authorization.server.issuer-uri.external=${AUTH_SERVER_EXTERNAL_URL:http://localhost:8083/auth-server}

server.servlet.context-path=/@project.name@
server.port=8080

springdoc.info.title=@project.name@
springdoc.info.version=@project.version@
springdoc.info.description=@project.description@

logging.level.root=${ROOT_LOG_LEVEL:ERROR}
logging.level.org.springframework=${SPRING_LOG_LEVEL:ERROR}
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.mongodb=INFO